wandb_version: 1

architecture:
  desc: null
  value: OpenLlama-3b-v2 VAE
steps:
  desc: null
  value: 100
_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.1
    framework: huggingface
    huggingface_version: 4.35.2
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1703862364.131219
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      2:
      - 1
      - 5
      - 11
      - 49
      - 51
      - 53
      - 55
      - 71
      - 98
      3:
      - 2
      - 16
      - 23
      4: 3.10.13
      5: 0.16.1
      6: 4.35.2
      8:
      - 1
      - 5
      13: linux-x86_64
